views/auth.py
from flask import Blueprint, current_app, redirect, render_template, request, session, url_for
from models import db, Note, AudioRecording, Users
from tools import generate_token

import datetime

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route("/login", methods = ['POST'])
def login():
    if db.session.query(Users).first().password == request.form.get('password') :
        session["logged_in"] = True
    else :
        session["home_message"] = "Wrong password"
    return redirect(url_for("routes.home"))

@auth.route("/logout", methods = ['GET'])
def logout():
    session.clear()
    session["home_message"] = "Logged out"
    return redirect(url_for("routes.home"))

@auth.route("/pwreset", methods = ['POST'])
def pwreset():
    session.clear()
    user = db.session.query(Users).first()
    db.session.delete(user)
    db.session.commit()
    session["home_message"] = "Password reset successful"
    return redirect(url_for("routes.home"))

@auth.route("/register", methods = ['POST'])
def register():
    if request.form.get('password') == request.form.get('password-confirm') :
        token, uuid = generate_token(request.form.get('password'))
        new_user = Users(
            password = request.form.get('password'),
            api_key = token,
            uuid = uuid,
            date_created = datetime.datetime.now())
        db.session.add(new_user)
        db.session.commit()

        session["logged_in"] = True
        session["settings_message"] = "Please copy your API key and input your swiftink key"
        return redirect(url_for("settings.root"))
    else :
        session["home_message"] = "The passwords did not match"
        return redirect(url_for("routes.home"))

views/settings.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from models import db, Users
from tools import generate_token

settings = Blueprint('settings', __name__, url_prefix='/settings')

@settings.route("/", methods = ['GET'])
def root():
    if session.get("logged_in") :
        user = db.session.query(Users).first()
        return render_template("settings.html", logged_in=True, api_key=user.api_key, swiftink_key=user.swiftink_api, message=session.get("settings_message"))
    else :
        return redirect(url_for("routes.home"))

@settings.route("/change", methods = ['POST'])
def change():
    if session.get("logged_in") :
        user = db.session.query(Users).first()
        message = ""

        if request.form.get('new-password') :
            if request.form.get('new-password') == request.form.get('new-password-confirm') :
                if request.form.get('old-password') == user.password :
                    user.password = request.form.get('new-password')
                    token, uuid = generate_token(request.form.get('new-password'))
                    user.api_key = token
                    user.uuid = uuid
                    message += "Successfully changed password. "
                else :
                    message += "Invalid password"
            else :
                message += "Passwords did not match. "

        if request.form.get('api_key') :
            token, uuid = generate_token(user.password)
            user.api_key = token
            user.uuid = uuid
            message += "Generated new API key. "

        if request.form.get('swiftink_key') :
            user.swiftink_api = request.form.get('swiftink_key')
            message += "Saved Swiftink API key. "

        db.session.commit()
        db.session.flush()

        session["settings_message"] = message
        return redirect("/settings")
    else :
        return redirect(url_for("routes.home"))

templates/auth.html
{% extends 'base.html' %}
{% set active = 'home' %}

{% block head %}
{{ super() }}
{% endblock%}

{% block content %}

<!-- Reset Modal -->
<div class="modal fade" id="resetModal" tabindex="-1" aria-labelledby="resetModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="resetModalLabel">Warning</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Reseting your password will also reset your API key. Proceed ?
      </div>
      <div class="modal-footer">
        <form action="{{ url_for('auth.pwreset')}}" method="POST" >
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            <button type="submit" class="btn btn-danger">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% if message %}
<div class="alert alert-info" role="alert">
    {{ message }}
</div>
{% endif %}

{% if registered %}
<form action="{{ url_for('auth.login')}}" enctype="application/x-www-form-urlencoded" method="POST">
    <div class="input-group mb-3">
        <span class="input-group-text" id="password-span">Password</span>
        <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="password">
    </div>
    <button class="btn btn-primary" type="submit">Login</button>
    <button class="btn btn-danger" type="button" data-bs-toggle="modal" data-bs-target="#resetModal">Reset Password</button>
</form>

{% else %}
<form action="{{ url_for('auth.register')}}" enctype="application/x-www-form-urlencoded" method="POST">
    <div class="input-group mb-3">
        <span class="input-group-text" id="password-span" style="width:10em">Password</span>
        <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="password">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="password-confirm-span" style="width:10em">Confirm password</span>
        <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="password-confirm">
    </div>
    <button class="btn btn-primary" type="submit">Register</button>
</form>
{% endif %}

{% endblock%}

templates/base.html
<!doctype html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <style type="text/css">
            .main-container {
              margin-top: 5%;
              margin-bottom: 5%;
              margin-left: 18%;
              margin-right: 18%;
              padding: 3%;
              border: 1px solid black;
              border-radius:.75rem!important;
              background-color: white;
              min-height: 80vh;
            }
            .content-container {
                padding: 5%
            }
            body {
                background-color: black!important;
            }
        </style>

        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        {% endblock %}
    </head>
    <body>
        <div class="main-container">
        <nav class="nav nav-tabs">
              <a class="navbar-brand" href="#">Obsidian Audio Capture</a>
              <ul class="nav nav-tabs">
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if active == 'home' }}" aria-current="page" href="{{ url_for('routes.home') }}">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {{ 'active' if active in ['captures', 'audio'] }} {{ 'disabled' if not logged_in }}" data-bs-toggle="dropdown" role="button" aria-expanded="false">Browse</a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item {{ 'active' if active == 'captures' }} {{ 'disabled' if not logged_in }}" href="#">Captures</a></li>
                      <li><a class="dropdown-item {{ 'active' if active == 'audio' }} {{ 'disabled' if not logged_in }}" href="#">Audio</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if active == 'guide' }} {{ 'disabled' if not logged_in }}" aria-disabled="true">API Guide</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if active == 'settings' }} {{ 'disabled' if not logged_in }}" href="{{url_for('settings.root')}}">Settings</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if active == 'logs' }} {{ 'disabled' if not logged_in }}" aria-disabled="true">Logs</a>
                  </li>
                </ul>
        </nav>
        <div class="content-container">
            {% block content %}
            {% endblock%}
        </div>
        </div>
        

        {{ bootstrap.load_js() }}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% set active = 'home' %}

{% block head %}
{{ super() }}
{% endblock%}

{% block content %}
<!-- Toasts -->
<div class="toast-container top-0 end-0 p-3">
  <div class="toast align-items-center text-bg-primary border-0" id="note-result-toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <div class="toast-body" id="note-result-toast-body"></div>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>

  <div class="toast align-items-center text-bg-primary border-0" id="audio-result-toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
        <div class="toast-body" id="audio-result-toast-body"></div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>

<!-- Forms -->
<div class="mb-3">
    <label for="formFile" class="form-label">Capture audio note</label>
    <input class="form-control" type="file" id="formFile" accept="audio/*">
</div>

<hr />

<label for="captureInput" class="form-label">Capture Note</label>
<div class="input-group">
    <span class="input-group-text">Capture</span>
    <textarea class="form-control" aria-label="With textarea" name="capture" id="captureInput"></textarea>
</div>
<br>
<div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="todoCheck" name="todo-check">
    <label class="form-check-label" for="todoCheck">Is a to-do item</label>
</div>
<br>
<button type="button" class="btn btn-primary" id="submitButton">Submit</button>


<script type="text/javascript" blocking="render" src="/static/home.js" swiftink-token="{{ user_info.api_key }}"></script>
{% endblock%}

templates/listen_audio.html
<!doctype html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <style type="text/css">
            .custom-container {
              margin: 5%;
              padding: 3%;
              border: 1px solid black;
              border-radius:.75rem!important;
              background-color: white;
              min-height: 80vh;
            }
            body {
                background-color: black!important;
            }
        </style>

        {{ bootstrap.load_css() }}
    </head>
    <body>
        <div class="custom-container">
        
        </div>
        {{ bootstrap.load_js() }}
    </body>
</html>

templates/settings.html
{% extends 'base.html' %}
{% set active = 'settings' %}

{% block head %}
{{ super() }}
{% endblock%}

{% block content %}
    {% if message %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
    {% endif %}
    
    <form action="{{ url_for('settings.change')}}" enctype="application/x-www-form-urlencoded" method="POST">
        <div class="input-group mb-3">
            <label class="form-label" labelfor="api_input">API Token</label>
            <div class="input-group">
                <input type="password" class="form-control" aria-label="api key" id="api_input" name="api_key" readonly="True" value="{{ api_key }}">
                <span class="input-group-text" id="show_hide_api">
                    <i class="bi bi-eye-slash" aria-hidden="true" id="api_eyei"></i>
                </span>
            </div>
        </div>
        <button class="btn btn-primary" type="button" id="api_key_copy">Copy</button>
        <button class="btn btn-danger" type="submit" data-bs-toggle="modal" data-bs-target="#resetModal">Regenerate API key</button>
    </form>

    <br>

    <form action="{{ url_for('settings.change')}}" enctype="application/x-www-form-urlencoded" method="POST">
        <div class="input-group mb-3">
            <label class="form-label" labelfor="swiftink_input">Swiftink API Token</label>
            <div class="input-group">
                <input type="password" class="form-control" aria-label="swiftink key" id="swiftink_input" name="swiftink_key" value="{{ swiftink_key }}">
                <span class="input-group-text" id="show_hide_swiftink">
                    <i class="bi bi-eye-slash" aria-hidden="true" id="swiftink_eyei"></i>
                </span>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Save</button>
        <button class="btn btn-danger" type="test" data-bs-toggle="modal" data-bs-target="#resetModal">Test</button>
    </form>

    <br>

    <form action="{{ url_for('settings.change')}}" enctype="application/x-www-form-urlencoded" method="POST">
            <label class="form-label" labelfor="old-password">Change Password (this will also regenerate your token)</label>
        <div class="input-group mb-3">
            <span class="input-group-text" id="old-password-span" style="width:12em">Old password</span>
            <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="old-password" id="old-password">
        </div>
        <br>
        <div class="input-group mb-3">
            <span class="input-group-text" id="new-password-span" style="width:12em">New password</span>
            <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="new-password">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="newpassword-confirm-span" style="width:12em">Confirm new password</span>
            <input type="password" class="form-control" aria-label="Username" aria-describedby="password-span" name="new-password-confirm">
        </div>
        <button class="btn btn-primary" type="submit">Change password</button>
    </form>

    <script type="text/javascript" blocking="render" src="/static/settings.js"></script>
{% endblock%}